<!DOCTYPE html>
<html>
<head>
    <title>PERFIL</title>
    <link rel="stylesheet" href="./styles/perfil.css">
    <link rel="shortcut icon" href="./img/logo.png">
</head>
<body>
    <br>
    <a href="./index.php"><button>ATRAS</button></a>
    <br>
    <div class="info">
        <div class="item">      
            <h2>PERFIL</h2> 
            <hr>
            <br>
            <label for="edad">Edad</label>
            <br>
            <br>
            <label for="correo">correo</label>
            <br>
            <br>
            <label for="localidad">localidad</label>

            </div>

            <div class="perfil">
                <div class="item">
                <img class="profile-picture" src="./imgandresimg.jpg" alt="imagen de perfil">
                <label for="cambiar" name="perfil"></label>
                <center><h1><label for="usuario">nombre usuario</label></h1></center>
                </div>
            </div>

            <div class="deceados">
            <label for=""><h2>DECEADOS</h2></label>
            <hr>
            </div>

    </div>
</body>
</html>