<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="./img/logo.png">
    <link rel="stylesheet" href="./styles/perfil.CSS">
    <title>AUSTES DE PERFIL</title>
</head>
<body>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias maiores, neque eligendi id laborum, magnam reiciendis expedita totam impedit dolorem accusantium, exercitationem aliquid quia. Voluptatibus nostrum quis porro animi quam?</p>
</body>
</html>

<?php

?>